# Stable
edition = "2021"
use_small_heuristics = "Max"
use_field_init_shorthand = true
use_try_shorthand = true

# Nightly
version = "Two"
wrap_comments = true
format_code_in_doc_comments = true
normalize_comments = true
normalize_doc_attributes = true
imports_granularity = "Crate"
group_imports = "StdExternalCrate"
reorder_impl_items = true
error_on_line_overflow = true
error_on_unformatted = true

# Future
report_fixme = "Always"
report_todo = "Always"
