name: Tests

on:
  push:
    branches: [ master, '0.[0-9]+' ]
  pull_request:
    branches: [ master, '0.[0-9]+' ]

permissions:
  contents: read #  to fetch code (actions/checkout)

jobs:
  check-doc:
    name: Check doc
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install Nix
        uses: DeterminateSystems/nix-installer-action@main
      - name: doc (rand)
        env:
          RUSTDOCFLAGS: --cfg doc_cfg
        # --all builds all crates, but with default features for other crates (okay in this case)
        run: nix develop --command cargo deadlinks --ignore-fragments -- --all --features wincode,chacha20,flate2,salsa20

  test:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: ubuntu-latest
            deps: cargo install cargo-all-features
            target: x86_64-unknown-linux-gnu
            toolchain: stable
          - os: macos-latest
            deps: cargo install cargo-all-features
            target: x86_64-apple-darwin
            toolchain: stable
          - os: windows-latest
            deps: cargo install cargo-all-features
            target: x86_64-pc-windows-gnu
            toolchain: stable
          - os: ubuntu-latest
            deps: sudo apt-get update ; sudo apt install gcc-multilib ; cargo install cargo-all-features
            target: i686-unknown-linux-gnu
            toolchain: stable

    steps:
      - uses: actions/checkout@v4
      - name: Install Nix
        if: matrix.os != 'windows-latest' && matrix.target != 'i686-unknown-linux-gnu'
        uses: DeterminateSystems/nix-installer-action@main
      - name: Install toolchain (Fallback)
        if: matrix.os == 'windows-latest' || matrix.target == 'i686-unknown-linux-gnu'
        uses: dtolnay/rust-toolchain@master
        with:
          target: ${{ matrix.target }}
          toolchain: ${{ matrix.toolchain }}
      - name: Install dependencies (Fallback)
        if: matrix.os == 'windows-latest' || matrix.target == 'i686-unknown-linux-gnu'
        run: ${{ matrix.deps }}
      - name: Test (Nix)
        if: matrix.os != 'windows-latest' && matrix.target != 'i686-unknown-linux-gnu'
        run: |
          nix develop --command bash -c "cargo test --target ${{ matrix.target }} --all-features && cargo all-features test --target ${{ matrix.target }}"
      - name: Test (Fallback)
        if: matrix.os == 'windows-latest' || matrix.target == 'i686-unknown-linux-gnu'
        run: |
          cargo test --target ${{ matrix.target }} --all-features
          cargo all-features test --target ${{ matrix.target }}

  test-ios:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install toolchain
        uses: dtolnay/rust-toolchain@stable
        with:
            target: aarch64-apple-ios
      - name: Build top-level only
        run: cargo build --target=aarch64-apple-ios
